### ISSUE TITLE
Missing letters

### ISSUE THREAD

**Issue by nervuri** [skyjake/lagrange#634]
I'm using Lagrange 1.17.0 on Debian 12 with the Sway window manager (Wayland).

Sometimes (seemingly) random bits of text go missing:

![2023-10-19](https://github.com/skyjake/lagrange/assets/34517938/f92ab33f-7c30-4f91-b124-4b948ecea428)

![2023-10-19_2](https://github.com/skyjake/lagrange/assets/34517938/2cf61483-722e-4cbc-859c-d9d66fe011c1)

Going to Preferences and changing the font temporarily fixes this, but not long after it happens again, no matter what font I choose.

**Comment by skyjake** [comment]
SDL's Wayland backend is known to have various issues and instability with Lagrange. This could be contributing here. Could you attach here your CMake build configuration, especially the various `ENABLE_*` variable options?

At a glance, the first screenshot looks like misplaced draws and the second one looks like missing glyphs in the font cache.

I have occasionally seen this type of visual artifacts, but in the past they have been resolved by switching to a newer version of SDL.

**Comment by nervuri** [comment]
> Could you attach here your CMake build configuration, especially the various `ENABLE_*` variable options?

```
//Draw a custom window frame (Windows)
ENABLE_CUSTOM_FRAME:BOOL=OFF

//Allow changing the Downloads directory
ENABLE_DOWNLOAD_EDIT:BOOL=ON

//Use the GNU FriBidi library for bidirectional text
ENABLE_FRIBIDI:BOOL=ON

//Build the GNU FriBidi library (if OFF, try pkg-config)
ENABLE_FRIBIDI_BUILD:BOOL=OFF

//Use the HarfBuzz library to shape text
ENABLE_HARFBUZZ:BOOL=OFF

//Build the HarfBuzz library with minimal dependencies (if OFF,
// try pkg-config)
ENABLE_HARFBUZZ_MINIMAL:BOOL=OFF

//While idle, sleep in the main thread instead of waiting for events
ENABLE_IDLE_SLEEP:BOOL=OFF

//Use IPC to communicate between running instances
ENABLE_IPC:BOOL=ON

//Enable kerning in font renderer (slower)
ENABLE_KERNING:BOOL=ON

//Use native context menus (macOS)
ENABLE_MAC_MENUS:BOOL=ON

//Use the phone mobile UI design instead of desktop UI
ENABLE_MOBILE_PHONE:BOOL=OFF

//Use the tablet mobile UI design instead of desktop UI
ENABLE_MOBILE_TABLET:BOOL=OFF

//Use mpg123 for decoding MPEG audio
ENABLE_MPG123:BOOL=OFF

//Use popup windows for context menus (if OFF, menus are confined
// inside main window)
ENABLE_POPUP_MENUS:BOOL=ON

//Resources should always be found via relative path
ENABLE_RELATIVE_EMBED:BOOL=OFF

//Force window to redraw during resizing
ENABLE_RESIZE_DRAW:BOOL=ON

//Use Sparkle for automatic updates (macOS)
ENABLE_SPARKLE:BOOL=OFF

//Enable the Curses TUI instead of GUI
ENABLE_TUI:BOOL=OFF

//Use libwebp to decode .webp images (via pkg-config)
ENABLE_WEBP:BOOL=OFF

//Set position after showing window (workaround for SDL bug)
ENABLE_WINDOWPOS_FIX:BOOL=OFF

//Use WinSparkle for automatic updates (Windows)
ENABLE_WINSPARKLE:BOOL=OFF

//Use software rendering (X11)
ENABLE_X11_SWRENDER:BOOL=OFF

//Use Xlib directly, if available (X11)
ENABLE_X11_XLIB:BOOL=ON
```

Is this what you need?

**Comment by skyjake** [comment]
Yes, thank you. Looks like you are using the "simple" text renderer that doesn't support RTL text and complex Unicode compositions (HarfBuzz disabled). Is this intentional?

The simple text renderer does use most of the same code as the more full-featured one, but since it's nowadays not the default renderer, bugs may have crept in there. I have a vague recollection that some glyph caching issues were fixed in the new text renderer but perhaps not in the simple one. I'll need to investigate...

**Comment by nervuri** [comment]
> Looks like you are using the "simple" text renderer that doesn't support RTL text and complex Unicode compositions (HarfBuzz disabled). Is this intentional?

Yes, I don't really need those complex Unicode features, so I had disabled HarfBuzz.  However, now I'm using v1.17.1 with HarfBuzz and the problem persists.  This time I compiled with:

```
ENABLE_FRIBIDI:BOOL=ON
ENABLE_FRIBIDI_BUILD:BOOL=ON
ENABLE_HARFBUZZ:BOOL=ON
```

Here's a glitch I haven't encountered before:

![2023-10-23_14:09:18](https://github.com/skyjake/lagrange/assets/34517938/a028594a-ed82-4a2d-ac45-2f87da7cc950)

**Comment by skyjake** [comment]
Since this hasn't been reported since by anyone else, I'm guessing the culprit is/was a video driver issue that is interacting badly with SDL, and not actually a bug in Lagrange itself.
